import { HttpClient } from "@angular/common/http";
import { Compiler, ModuleWithProviders } from "@angular/core";
import { NbIconLibraries } from "@nebular/theme";
import { Router } from "@angular/router";
import { RestAdminConfigService } from "./rest-admin/rest-resource/service/rest-admin-config.service";
import { REST_CONFIG } from "./rest-admin/rest-resource/models/rest-resource.model";
import { TranslateHttpLoader } from "@ngx-translate/http-loader";
import { RestLangService } from "./rest-admin/rest-resource/service/rest-lang.service";
import * as i0 from "@angular/core";
import * as i1 from "./rest-admin/rest-resource/rest-resource-list/rest-resource-list.component";
import * as i2 from "./rest-admin/rest-resource/rest-resource-add/rest-resource-add.component";
import * as i3 from "./rest-admin/rest-resource/rest-ressource-delete/rest-resource-delete.component";
import * as i4 from "./rest-admin/rest-main-component/rest-main-component.component";
import * as i5 from "./rest-admin/rest-resource/components/rest-resource-editor-fields/rest-resource-editor-fields.component";
import * as i6 from "./rest-admin/rest-resource/components/rest.resource-list-field/rest.resource-list-field.component";
import * as i7 from "./rest-admin/rest-resource/rest-resource-detail/rest-resource-detail.component";
import * as i8 from "./rest-admin/rest-resource/components/upload-file/upload-file.component";
import * as i9 from "./rest-admin/rest-resource/components/fs-icon-ccomponent/fs-icon.component";
import * as i10 from "@angular/common";
import * as i11 from "@angular/router";
import * as i12 from "@angular/forms";
import * as i13 from "@angular/common/http";
import * as i14 from "@nebular/theme";
import * as i15 from "ng2-smart-table";
import * as i16 from "@iplab/ngx-file-upload";
import * as i17 from "@codehint-ng/html-compiler";
import * as i18 from "ngx-image-cropper";
import * as i19 from "@ngx-translate/core";
import * as i20 from "ngx-dropzone";
import * as i21 from "ngx-permissions";
import * as i22 from "./@core/core.module";
import * as i23 from "./@theme/theme.module";
export declare function createTranslateHttpLoader(http: HttpClient): TranslateHttpLoader;
export declare class RestAdminModule {
    private router;
    private compiler;
    private serviceRestAdmin;
    private iconLibraries;
    private restLangService;
    constructor(router: Router, compiler: Compiler, serviceRestAdmin: RestAdminConfigService, iconLibraries: NbIconLibraries, restLangService: RestLangService);
    static forRoot(restConfig: REST_CONFIG): ModuleWithProviders<RestAdminModule>;
    static ɵfac: i0.ɵɵFactoryDeclaration<RestAdminModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<RestAdminModule, [typeof i1.RestResourceListComponent, typeof i2.RestResourceAddComponent, typeof i3.RestResourceDeleteComponent, typeof i4.RestMainComponentComponent, typeof i5.RestResourceEditorFieldsComponent, typeof i6.RestResourceListFieldComponent, typeof i7.RestResourceDetailComponent, typeof i8.UploadFileComponent, typeof i9.FsIconCComponent], [typeof i10.CommonModule, typeof i11.RouterModule, typeof i12.ReactiveFormsModule, typeof i12.FormsModule, typeof i13.HttpClientModule, typeof i14.NbActionsModule, typeof i14.NbButtonModule, typeof i14.NbCardModule, typeof i14.NbCheckboxModule, typeof i14.NbInputModule, typeof i14.NbTagModule, typeof i14.NbRadioModule, typeof i14.NbUserModule, typeof i14.NbTreeGridModule, typeof i14.NbAutocompleteModule, typeof i15.Ng2SmartTableModule, typeof i16.FileUploadModule, typeof i17.CngHtmlCompilerModule, typeof i14.NbSpinnerModule, typeof i14.NbTabsetModule, typeof i14.NbPopoverModule, typeof i18.ImageCropperModule, typeof i14.NbToggleModule, typeof i14.NbListModule, typeof i14.NbTooltipModule, typeof i14.NbContextMenuModule, typeof i19.TranslateModule, typeof i20.NgxDropzoneModule, typeof i21.NgxPermissionsModule, typeof i14.NbSelectModule, typeof i14.NbSidebarModule, typeof i14.NbMenuModule, typeof i14.NbDatepickerModule, typeof i14.NbDialogModule, typeof i14.NbWindowModule, typeof i14.NbToastrModule, typeof i14.NbTimepickerModule, typeof i22.CoreModule, typeof i23.ThemeModule, typeof i14.NbIconModule, typeof i19.TranslateModule], [typeof i1.RestResourceListComponent, typeof i2.RestResourceAddComponent, typeof i3.RestResourceDeleteComponent, typeof i4.RestMainComponentComponent, typeof i5.RestResourceEditorFieldsComponent, typeof i6.RestResourceListFieldComponent, typeof i7.RestResourceDetailComponent, typeof i8.UploadFileComponent]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<RestAdminModule>;
}
